baseurl                  = "https://lamia.netlity.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Lamia's notes"
theme = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "Std_R_pie.png"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "Lamia's notes"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Lamia's notes"

[[params.mainMenu]]
    link = "/notes"
    text = "notes"

[[params.mainMenu]]
    link = "/visual"
    text = "visual notes"

[[params.mainMenu]]
    link = "/photography"
    text = "photography"

[[params.mainMenu]]
    link = "/about"
    text = "about me"

[imaging]
    quality = 75
